---
- name: Create fish directory
  file:
    path: ~/.config/fish
    state: directory

- name: Create symbolic link
  file: src={{ item }} dest=~/.config/fish/{{ item | basename }} state=link force=yes
  with_fileglob:
    - ./*

- name: Install fisherman
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish

- name: Download powerline fonts
  unarchive:
    src: https://github.com/powerline/fonts/archive/master.zip
    dest: ./
    remote_src: true

- name: Install powerline fonts
  command: ./install.sh arg1
  args:
    chdir: fonts-master

- debug:
  msg: "Please execute fisher command to install fish plugins"
