---
- name: Create fish directory
  file:
    path: ~/.config/fish
    state: directory

- name: Create symbolic link
  file: src={{ item }} dest=~/.config/fish/{{ item | basename }} state=link force=yes
  with_fileglob:
    - ./*

- name: Install fisherman
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish

- debug:
  msg: "Please execute fisher command to install fish plugins"
