---
- name: Create synbolic link
  file: src={{ item }} dest=~/.{{ item | basename }} state=link force=yes
  with_fileglob:
    - ./*

- name: Create directories for fish
  file: path=~/.config/fish state=directory
